# Generated by Django 4.2.6 on 2023-10-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_cavaleiro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavaleiro',
            name='imagem',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
