# Generated by Django 4.2.6 on 2023-10-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_cavaleiro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavaleiro',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='galeria/%Y%m'),
        ),
    ]
