# Generated by Django 4.2.6 on 2023-10-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_cavaleiro_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavaleiro',
            name='categoria',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('OURO', 'Ouro'), ('PRATA', 'Prata')], default='', max_length=100),
        ),
    ]
