# Generated by Django 4.2.6 on 2023-10-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_alter_cavaleiro_armadura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavaleiro',
            name='armadura',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('OURO', 'Ouro'), ('PRATA', 'Prata')], default='', max_length=100),
        ),
    ]
