# Generated by Django 4.2.6 on 2023-10-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cavaleiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('constelacao', models.CharField(max_length=100)),
                ('historia', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
