# Generated by Django 4.2.6 on 2023-10-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavaleiro',
            name='imagem',
            field=models.ImageField(upload_to='assets/imagens/galeria/%Y%m'),
        ),
    ]
