# Generated by Django 4.2.6 on 2023-10-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_cavaleiro_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cavaleiro',
            old_name='categoria',
            new_name='armadura',
        ),
    ]
